#ifndef JAVAN_RUNTIME_H
#define JAVAN_RUNTIME_H

void javan_println(const char* value);
void javan_println_int(int value);
void javan_println_long(long long value);
void javan_println_float(float value);
void javan_println_double(double value);
void javan_println_bool(int value);
int javan_math_abs_int(int value);
long long javan_math_abs_long(long long value);
int javan_math_min_int(int left, int right);
long long javan_math_min_long(long long left, long long right);
int javan_math_max_int(int left, int right);
long long javan_math_max_long(long long left, long long right);
long long javan_system_nano_time(void);
long long javan_system_current_time_millis(void);
void javan_system_arraycopy(void* source, int source_position, void* target, int target_position, int length);
void* javan_objects_require_non_null(void* value);
typedef struct {
    signed char* data;
    int length;
} JavanByteArray;
void* javan_alloc(unsigned long size);
void javan_free(void* value);
void* javan_object_array_new(int length);
void* javan_object_array_get(void* array, int index);
void javan_object_array_set(void* array, int index, void* value);
void* javan_int_array_new(int length);
int javan_int_array_get(void* array, int index);
void javan_int_array_set(void* array, int index, int value);
void* javan_long_array_new(int length);
long long javan_long_array_get(void* array, int index);
void javan_long_array_set(void* array, int index, long long value);
void* javan_float_array_new(int length);
float javan_float_array_get(void* array, int index);
void javan_float_array_set(void* array, int index, float value);
void* javan_double_array_new(int length);
double javan_double_array_get(void* array, int index);
void javan_double_array_set(void* array, int index, double value);
void* javan_byte_array_new(int length);
void* javan_boolean_array_new(int length);
int javan_byte_array_get(void* array, int index);
void javan_byte_array_set(void* array, int index, int value);
void* javan_byte_array_from(const signed char* data, int length);
JavanByteArray javan_byte_array_export(void* array);
void* javan_short_array_new(int length);
int javan_short_array_get(void* array, int index);
void javan_short_array_set(void* array, int index, int value);
void* javan_char_array_new(int length);
int javan_char_array_get(void* array, int index);
void javan_char_array_set(void* array, int index, int value);
int javan_array_length(void* array);
void* javan_arrays_copy_of_object(void* array, int new_length);
void* javan_arrays_copy_of_int(void* array, int new_length);
void* javan_arrays_copy_of_long(void* array, int new_length);
void* javan_arrays_copy_of_float(void* array, int new_length);
void* javan_arrays_copy_of_double(void* array, int new_length);
void* javan_arrays_copy_of_byte(void* array, int new_length);
void* javan_arrays_copy_of_short(void* array, int new_length);
void* javan_arrays_copy_of_char(void* array, int new_length);
void* javan_string_array_from_args(int argc, char** argv);
int javan_string_length(const char* value);
int javan_string_is_empty(const char* value);
int javan_string_char_at(const char* value, int index);
int javan_string_equals(const char* left, const char* right);
void* javan_string_value_of_int(int value);
void* javan_string_value_of_long(long long value);
void* javan_string_value_of_float(float value);
void* javan_string_value_of_double(double value);
void* javan_string_value_of_bool(int value);
void* javan_string_value_of_char(int value);
void* javan_string_concat(const char* recipe, int argc, const char** values);
char* javan_string_export(const char* value);
int javan_float_compare(float left, float right, int nan_value);
int javan_double_compare(double left, double right, int nan_value);
void javan_panic(const char* value);

#endif
