package javan.classfile;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Parsed Java method metadata.
 *
 * @param accessFlags method access flags
 * @param name method name
 * @param descriptor method descriptor
 * @param code method bytecode when present
 */
public record MethodInfo(int accessFlags, String name, String descriptor, Optional<CodeAttribute> code) {
    private static final int ACC_PUBLIC = 0x0001;
    private static final int ACC_PRIVATE = 0x0002;
    private static final int ACC_SYNCHRONIZED = 0x0020;
    private static final int ACC_STATIC = 0x0008;
    private static final int ACC_NATIVE = 0x0100;
    private static final int ACC_SYNTHETIC = 0x1000;

    /**
     * Returns the internal class names referenced by object and object-array parameters.
     *
     * <p>Primitive arrays are omitted. Object-array component types are retained because bytecode may
     * load and throw an element.</p>
     *
     * @return immutable reference parameter names in declaration order
     * @throws IllegalStateException when the parsed method descriptor is malformed
     */
    public List<String> referencedParameterTypes() {
        final List<String> result = new ArrayList<>();
        int index = 1;
        while (index < descriptor.length() && descriptor.charAt(index) != ')') {
            final char type = descriptor.charAt(index);
            if ("BCDFIJSZ".indexOf(type) >= 0) {
                index++;
                continue;
            }
            if (type == 'L') {
                final int end = descriptor.indexOf(';', index);
                if (end < 0) {
                    throw new IllegalStateException("Malformed method descriptor: " + descriptor);
                }
                result.add(descriptor.substring(index + 1, end));
                index = end + 1;
                continue;
            }
            if (type == '[') {
                do {
                    index++;
                } while (index < descriptor.length() && descriptor.charAt(index) == '[');
                if (index >= descriptor.length()) {
                    throw new IllegalStateException("Malformed method descriptor: " + descriptor);
                }
                if (descriptor.charAt(index) == 'L') {
                    final int end = descriptor.indexOf(';', index);
                    if (end < 0) {
                        throw new IllegalStateException("Malformed method descriptor: " + descriptor);
                    }
                    result.add(descriptor.substring(index + 1, end));
                    index = end + 1;
                } else if ("BCDFIJSZ".indexOf(descriptor.charAt(index)) >= 0) {
                    index++;
                } else {
                    throw new IllegalStateException("Malformed method descriptor: " + descriptor);
                }
                continue;
            }
            throw new IllegalStateException("Malformed method descriptor: " + descriptor);
        }
        if (!descriptor.startsWith("(") || index >= descriptor.length()) {
            throw new IllegalStateException("Malformed method descriptor: " + descriptor);
        }
        return List.copyOf(result);
    }

    /**
     * Returns true when this method is {@code public static void main(String[])}.
     *
     * @return true for the Java main method shape
     */
    public boolean isPublicStaticMain() {
        if (!"main".equals(name)) {
            return false;
        }
        if (!"([Ljava/lang/String;)V".equals(descriptor)) {
            return false;
        }
        if ((accessFlags & ACC_PUBLIC) == 0) {
            return false;
        }
        if ((accessFlags & ACC_STATIC) == 0) {
            return false;
        }
        return true;
    }

    /**
     * Returns true when the method is public.
     *
     * @return true when public
     */
    public boolean isPublic() {
        return (accessFlags & ACC_PUBLIC) != 0;
    }

    /**
     * Returns true when the method is static.
     *
     * @return true when static
     */
    public boolean isStatic() {
        if ((accessFlags & ACC_STATIC) == 0) {
            return false;
        }
        return true;
    }

    /**
     * Returns true when this method is private to its declaring class or interface.
     *
     * @return true when private
     */
    public boolean isPrivate() {
        return (accessFlags & ACC_PRIVATE) != 0;
    }

    /**
     * Returns true when the method is native.
     *
     * @return true when native
     */
    public boolean isNative() {
        if ((accessFlags & ACC_NATIVE) == 0) {
            return false;
        }
        return true;
    }

    /**
     * Returns true when this method was generated by the bytecode compiler.
     *
     * @return true when synthetic
     */
    public boolean isSynthetic() {
        if ((accessFlags & ACC_SYNTHETIC) == 0) {
            return false;
        }
        return true;
    }

    /**
     * Returns true when the method is synchronized.
     *
     * @return true when synchronized
     */
    public boolean isSynchronized() {
        if ((accessFlags & ACC_SYNCHRONIZED) == 0) {
            return false;
        }
        return true;
    }
}
